post http://localhost:3000/api/events
Content-Type: application/json
 
{
  "name":"Jumanji",
  "description":"Dangerous game",
  "time":"2:00",
  "dates":[
    {"day":10,"month":5,"year":2020},
    {"day":10,"month":6,"year":2020},
    {"day":10,"month":7,"year":2020}
  ],
  "registered":[]
}